const TYPES = {
  FETCH_ALL_CHATS_REQUEST: Symbol('FETCH_ALL_CHATS_REQUEST'),
  FETCH_ALL_CHATS_SUCCESS: Symbol('FETCH_ALL_CHATS_SUCCESS'),
  FETCH_ALL_CHATS_FAILURE: Symbol('FETCH_ALL_CHATS_FAILURE'),

  FETCH_MY_CHATS_REQUEST: Symbol('FETCH_MY_CHATS_REQUEST'),
  FETCH_MY_CHATS_SUCCESS: Symbol('FETCH_MY_CHATS_SUCCESS'),
  FETCH_MY_CHATS_FAILURE: Symbol('FETCH_MY_CHATS_FAILURE'),

  SET_ACTIVE_CHAT: Symbol('SET_ACTIVE_CHAT'),
  UNSET_ACTIVE_CHAT: Symbol('UNSET_ACTIVE_CHAT'),

  FETCH_CHAT_REQUEST: Symbol('FETCH_CHAT_REQUEST'),
  FETCH_CHAT_SUCCESS: Symbol('FETCH_CHAT_SUCCESS'),
  FETCH_CHAT_FAILURE: Symbol('FETCH_CHAT_FAILURE'),

  CREATE_CHAT_REQUEST: Symbol('CREATE_CHAT_REQUEST'),
  CREATE_CHAT_SUCCESS: Symbol('CREATE_CHAT_SUCCESS'),
  CREATE_CHAT_FAILURE: Symbol('CREATE_CHAT_FAILURE'),

  DELETE_CHAT_REQUEST: Symbol('DELETE_CHAT_REQUEST'),
  DELETE_CHAT_SUCCESS: Symbol('DELETE_CHAT_SUCCESS'),
  DELETE_CHAT_FAILURE: Symbol('DELETE_CHAT_FAILURE'),

  JOIN_CHAT_REQUEST: Symbol('JOIN_CHAT_REQUEST'),
  JOIN_CHAT_SUCCESS: Symbol('JOIN_CHAT_SUCCESS'),
  JOIN_CHAT_FAILURE: Symbol('JOIN_CHAT_FAILURE'),

  LEAVE_CHAT_REQUEST: Symbol('LEAVE_CHAT_REQUEST'),
  LEAVE_CHAT_SUCCESS: Symbol('LEAVE_CHAT_SUCCESS'),
  LEAVE_CHAT_FAILURE: Symbol('LEAVE_CHAT_FAILURE'),

  SEND_MESSAGE_REQUEST: Symbol('SEND_MESSAGE_REQUEST'),
  SEND_MESSAGE_SUCCESS: Symbol('SEND_MESSAGE_SUCCESS'),
  SEND_MESSAGE_FAILURE: Symbol('SEND_MESSAGE_FAILURE'),
}

export default TYPES
