const TYPES = {
  FETCH_ALL_CHATS_REQUEST: Symbol('FETCH_ALL_CHATS_REQUEST'),
  FETCH_ALL_CHATS_SUCCESS: Symbol('FETCH_ALL_CHATS_SUCCESS'),
  FETCH_ALL_CHATS_FAILURE: Symbol('FETCH_ALL_CHATS_FAILURE'),

  FETCH_MY_CHATS_REQUEST: Symbol('FETCH_MY_CHATS_REQUEST'),
  FETCH_MY_CHATS_SUCCESS: Symbol('FETCH_MY_CHATS_SUCCESS'),
  FETCH_MY_CHATS_FAILURE: Symbol('FETCH_MY_CHATS_FAILURE'),

  SET_ACTIVE_CHAT: Symbol('SET_ACTIVE_CHAT'),
  UNSET_ACTIVE_CHAT: Symbol('UNSET_ACTIVE_CHAT'),

  FETCH_CHAT_REQUEST: Symbol('FETCH_CHAT_REQUEST'),
  FETCH_CHAT_SUCCESS: Symbol('FETCH_CHAT_SUCCESS'),
  FETCH_CHAT_FAILURE: Symbol('FETCH_CHAT_FAILURE'),
}

export default TYPES
