export const SIGNUP_REQUEST = Symbol('SIGNUP_REQUEST');
export const SIGNUP_SUCCESS = Symbol('SIGNUP_SUCCESS');
export const SIGNUP_FAILURE = Symbol('SIGNUP_FAILURE');

export const LOGIN_REQUEST = Symbol('LOGIN_REQUEST');
export const LOGIN_SUCCESS = Symbol('LOGIN_SUCCESS');
export const LOGIN_FAILURE = Symbol('LOGIN_FAILURE');

export const LOGOUT_REQUEST = Symbol('LOGOUT_REQUEST');
export const LOGOUT_SUCCESS = Symbol('LOGOUT_SUCCESS');
export const LOGOUT_FAILURE = Symbol('LOGOUT_FAILURE');

const TYPES = {
  SIGNUP_REQUEST: Symbol('SIGNUP_REQUEST'),
  SIGNUP_SUCCESS: Symbol('SIGNUP_SUCCESS'),
  SIGNUP_FAILURE: Symbol('SIGNUP_FAILURE'),

  LOGIN_REQUEST: Symbol('LOGIN_REQUEST'),
  LOGIN_SUCCESS: Symbol('LOGIN_SUCCESS'),
  LOGIN_FAILURE: Symbol('LOGIN_FAILURE'),

  LOGOUT_REQUEST: Symbol('LOGOUT_REQUEST'),
  LOGOUT_SUCCESS: Symbol('LOGOUT_SUCCESS'),
  LOGOUT_FAILURE: Symbol('LOGOUT_FAILURE'),
}

export default TYPES
